services:
  backend:
    build: .
    container_name: mikhmon-admin-api
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=mysql://pepadu:pepadu@host.docker.internal:3306/admin_db
      - MIKHMON_DATABASE_URL=mysql://mikhmon_user:mikhmon_pass123@host.docker.internal:3306/mikhmon
      - HOST=0.0.0.0
      - PORT=8080
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: mikhmon-admin-ui
    restart: always
    ports:
      - "8089:80"
    depends_on:
      - backend
